---
galaxy_info:
  author: Marcos Amorim
  company: Red Hat
  license: Apache
  min_ansible_version: 1.9
  platforms:
   - name: EL
     versions:
      - 5
      - 6
      - 7
  categories:
    - networking
    - system
    - openstack
    - openvswitch
dependencies: []
  
