---
# file: roles/rabbitmq/default/main.yml
# CONFIG
rabbitmq_firewalld: true
rabbitmq_erlang_cookie: 'AbCd3rl4ngC00k13WxYz'
rabbitmq_clustering: true
rabbitmq_env_vars: true
rabbitmq_cluster_name: rabbit
rabbitmq_reset_cluster: false
rabbitmq_management_plugin: true
rabbitmq_ssl: false
rabbitmq_bind_address: 0.0.0.0
rabbitmq_port: 5672
rabbitmq_fd_limits: 4096
rabbitmq_vm_memory: 0.4
rabbitmq_vm_memory_ratio: 0.5
rabbitmq_mem_relative: 1.0
rabbitmq_heartbeat: 10

# SSL
rabbitmq_cacert_file: etc/rabbitmq/ssl/cacert.pem
rabbitmq_cert_file: etc/rabbitmq/ssl/cert.pem
rabbitmq_key_file: etc/rabbitmq/ssl/key.pem
rabbitmq_ssl_bind_address: 0.0.0.0
rabbitmq_ssl_port: 5671

# VHOSTS
rabbitmq_vhost_list:
  - name: glance
  - name: nova
  - name: cinder
  - name: ceilometer
  - name: heat
  - name: keystone
  - name: trove

# USERS
rabbitmq_users_list:
  - vhost: glance
    user: glance
    password: "{{ rabbitmq_glance_password | default('gl4nc3p4ssw0rd') }}"
  - vhost: nova
    user: nova
    password: "{{ rabbitmq_nova_password | default('n0v4p4ssw0rd') }}"
  - vhost: cinder
    user: cinder
    password: "{{ rabbitmq_cinder_password | default('cind3rp4ssw0rd') }}"
  - vhost: ceilometer
    user: ceilometer
    password: "{{ rabbitmq_ceilometer_password | default('ceil0m3terp4ssw0rd') }}"
  - vhost: heat
    user: heat
    password: "{{ rabbitmq_heat_password | default('he4tp4ssw0rd') }}"
  - vhost: keystone
    user: keystone
    password: "{{ rabbitmq_keystone_password | default('keyst0n3p4ssw0rd') }}"
  - vhost: trove
    user: trove
    password: "{{ rabbitmq_trove_password | default('tr0vep4ssw0rd') }}"
  - vhost: /
    user: admin
    password: "{{ rabbitmq_admin_password }}"
    tags:
    - administrator

# POLICIES
rabbitmq_policies_list:
  - name: HA-Glance
    pattern: .*
    tags:
      ha-mode: all
    vhost: glance
  - name: HA-Nova
    pattern: .*
    tags:
      ha-mode: all
    vhost: nova
  - name: HA-Cinder
    pattern: .*
    tags:
      ha-mode: all
    vhost: cinder
  - name: HA-Ceilometer
    pattern: .*
    tags:
      ha-mode: all
    vhost: ceilometer
  - name: HA-Heat
    pattern: .*
    tags:
      ha-mode: all
    vhost: heat
  - name: HA-Keystone
    pattern: .*
    tags:
      ha-mode: all
    vhost: keystone
  - name: HA-Trove
    pattern: .*
    tags:
      ha-mode: all
    vhost: trove
  - name: HA
    pattern: .*
    tags:
      ha-mode: all
    vhost: /

# FIREWALL PORTS
fw_epmd: 4369/tcp
fw_erlang_distrib: 25672/tcp
fw_rabbitmq: 5672/tcp
fw_rabbitmq_ssl: 5671/tcp
fw_management: 15672/tcp

