---

- name: Deleting galera config file
  file:
    path=/etc/my.cnf.d/galera.cnf
    state=absent

- include: selinux.yml
  when: galera_selinux is defined and
        galera_selinux == true

- name: set bind address to local ip
  ini_file: >
    dest=/etc/my.cnf
    section=mysqld
    option=bind-address
    value={{ mariadb_bind_address }}
    state=present

- name: Starting MariaDB service
  command: systemctl restart mariadb
  when: inventory_hostname == galera_master

- name: Set root password for localhost
  mysql_user:
    name=root
    password={{ mariadb_root_password }}
    host=localhost
    state=present
  when: inventory_hostname == galera_master

- name: Creating the /root/.my.cnf file
  ini_file: >
    dest=/root/.my.cnf
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=root
    owner=root
    mode=0600
  with_items: "{{ mycnf_options }}"

- name: Configuring Galera cluster (RedHat family)
  template:
    src=etc/my.cnf.d/server.cnf.j2
    dest=/etc/my.cnf.d/server.cnf

- name: Removing wap-wsp* services from /etc/services
  lineinfile:
    dest=/etc/services
    state=absent
    regexp="^wap-wsp         {{ galera_xinet_port}}"

- name: Adding mysqlchk /etc/services
  lineinfile:
    dest=/etc/services
    state=present
    regexp="^mysqlchk"
    insertafter="sun-as-jpda     9191/udp"
    line="mysqlchk        {{ galera_xinet_port }}/tcp                \# Galera Clustercheck"

- name: Adding galera-status script in /usr/bin/
  copy:
    src=usr/bin/galera-status
    dest=/usr/bin/galera-status
    mode=0755

- name: create clustercheck
  copy:
    src=usr/bin/clustercheck
    dest=/usr/bin/clustercheck
    mode=0755

- name: create xinetd clustercheck
  template:
    src=etc/xinetd.d/galera-stream.j2
    dest=/etc/xinetd.d/galera-stream

- name: create default clustercheck
  template:
    src=etc/sysconfig/clustercheck.j2
    dest=/etc/sysconfig/clustercheck

- name: Fix correct wrep cluster address
  ini_file: >
    dest=/etc/my.cnf.d/server.cnf
    section="galera"
    option="wsrep_cluster_address"
    value="gcomm://{{ ','.join(galera_hosts) }}"
  when: inventory_hostname != galera_master

- name: create services.d directory to mariadb
  file:
    dest=/etc/systemd/system/mariadb.service.d
    state=directory

- name: set limits to mariadb
  ini_file:
    dest=/etc/systemd/system/mariadb.service.d/limits.conf
    section=Service
    option=LimitNOFILE
    value=16384
  notify: systemctl daemon reload

- name: Finalize the setup by creating file /etc/mysql_clustered
  copy:
    content="Cluster created:{{ ansible_date_time.date }}"
    dest=/etc/mysql_clustered
    owner=mysql
    group=mysql
