---

- name: Force delete a Galera cluster if already exists
  file:
    path=/etc/mysql_clustered
    state=absent
  when: galera_reset_cluster is defined and
        galera_reset_cluster

- name: Checking if a Galera cluster already exists
  stat:
    path=/etc/mysql_clustered
  register: galera_clustered

- name: Include galera packages
  include: packages.yml
  when: galera_clustered.stat.exists != True

- name: include galera reset
  include: reset.yml
  when: galera_reset_cluster is defined and
        galera_reset_cluster

- name: Fix mariadb permissions
  file:
    dest=/var/log/mariadb/mariadb.log
    owner=mysql
    group=mysql
    state=file
  ignore_errors: True

- name: include galera firewall
  include: firewall.yml
  when: galera_firewalld is defined and
        galera_firewalld and
        galera_clustered.stat.exists != True

- name: Stop firewalld
  service: name=firewalld state=stopped
  when: not galera_firewalld

- name: include galera configuration
  include: configuration.yml
  when: galera_clustered.stat.exists != True

- name: include galera secure
  include: secure.yml
  when: galera_clustered.stat.exists != True

- name: include galera users
  include: user.yml
  when: galera_clustered.stat.exists != True

- name: include galera bootstrap
  include: bootstrap.yml
  when: galera_clustered.stat.exists != True

- name: include galera databases
  include: databases.yml
  when: galera_clustered.stat.exists != True

- name: include galera sanity check
  include: sanitycheck.yml
  when: galera_clustered.stat.exists != True

- name: include galera pacemaker
  include: pacemaker.yml
