---

- name: disable mariadb from boot
  service: name=mariadb enabled=no state=stopped

- name: Creating /etc/sysconfig/clustercheck file (ready for Pacemaker)
  template:
    src=etc/sysconfig/clustercheck.j2
    dest=/etc/sysconfig/clustercheck
  tags:
    - galera
    - galera-clustercheck

- name: Creating /usr/bin/clustercheck file (ready for Pacemaker)
  copy:
    src=usr/bin/clustercheck
    dest=/usr/bin/clustercheck
    mode=0755
  tags:
    - galera
    - galera-clustercheck

- name: Creating /etc/xinet.d/galera-stream file (ready for Pacemaker)
  template:
    src=etc/xinetd.d/galera-stream.j2
    dest=/etc/xinetd.d/galera-stream
    mode=0600
  tags:
    - galera
    - galera-clustercheck

- name: Enabling and starting xinetd service (ready for Pacemaker)
  service:
    name=xinetd
    state=started
    enabled=yes
  tags:
    - galera
    - galera-clustercheck

- name: stop mariadb before add to pacemaker
  service: name=mariadb state=stopped enabled=no

- name: Deleting wsrep_cluster_address option (ready for Pacemaker)
  lineinfile:
    dest=/etc/{{ mariadb_config }}
    state=absent
    regexp='^wsrep_cluster_address='

- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  tags:
    - pacemaker
    - pacemaker-galera

- name: create galera cluster resource
  command:
    pcs resource create galera galera enable_creation=true wsrep_cluster_address="gcomm://{{ galera_node_names|join(',')}}" meta master-max=3 ordered=true op promote timeout=300s on-fail=block --master
  when: ansible_hostname == pacemaker_dc.stdout
  tags:
    - pacemaker
    - pacemaker-galera


# TODO: Create constraints to galera
