---
- name: Remove galera from pacemaker
  command: pcs resource delete galera
  when: inventory_hostname == master_server
  ignore_errors: True

- name: Stopping/killing MariaDB service
  shell: pkill -9 -u mysql || true
  ignore_errors: True

- name: Purging MariaDB data directory
  file:
    path: "{{ mariadb_datadir }}"
    state: absent
    force: yes
  ignore_errors: True

- name: Rebuilding MariaDB data
  command: /usr/bin/mysql_install_db
  when: ansible_os_family == 'RedHat'
  ignore_errors: True

- name: Restoring permissions on MariaDB data directory
  file:
    path: "{{ mariadb_datadir }}"
    owner: mysql
    group: mysql
    recurse: yes
  ignore_errors: True

- name: Relabeling MariaDB data directory
  command: /usr/sbin/restorecon -R {{ mariadb_datadir }}
  ignore_errors: True

- name: Deleting MariaDB configs files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/{{ mariadb_config }}"
    - /root/.my.cnf
    - /etc/my.cnf.d/server.cnf
    - /etc/sysconfig/clustercheck
    - /usr/bin/clustercheck
  ignore_errors: True
