---
- name: Stopping/killing MariaDB service
  shell: pkill -9 -u mysql || true
  ignore_errors: True
  no_log: True

- name: Purging MariaDB data directory
  file:
    path={{ mariadb_datadir }}
    state=absent
    force=yes
  ignore_errors: True
  no_log: True

- name: Rebuilding MariaDB data
  command: /usr/bin/mysql_install_db
  when: ansible_os_family == 'RedHat'
  ignore_errors: True
  no_log: True

- name: Restoring permissions on MariaDB data directory
  file:
    path={{ mariadb_datadir }}
    owner=mysql
    group=mysql
    recurse=yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: True
  no_log: True

- name: Relabeling MariaDB data directory
  command: /usr/sbin/restorecon -R {{ mariadb_datadir }}
  when: ansible_os_family == 'RedHat'
  ignore_errors: True
  no_log: True

- name: Deleting MariaDB config file
  file:
    path=/etc/{{ mariadb_config }}
    state=absent
  ignore_errors: True
  no_log: True

- name: Deleting /root/.my.cnf file
  file:
    path=/root/.my.cnf
    state=absent
  ignore_errors: True
  no_log: True

- name: Deleting Cluster MariaDB
  file:
    path=/etc/my.cnf.d/server.cnf
    state=absent
  ignore_errors: True
  no_log: True
