---
# file: roles/galera/tasks/selinux.yml
- name: Building and installing SELinux module
  copy:
    src=selinux/galera_cluster.te
    dest=/tmp/

- command:
    /usr/bin/checkmodule -M -m -o galera_cluster.mod /tmp/galera_cluster.te
- command:
    /usr/bin/semodule_package -m galera_cluster.mod -o /tmp/galera_cluster.pp
- command:
    /usr/sbin/semodule -i /tmp/galera_cluster.pp

- seport:
    ports={{ mariadb_port }},{{ fw_mysql_ist }},{{ fw_mysql_sst }},{{ fw_galera }},{{ fw_xinetd }}
    proto=tcp
    setype=mysqld_port_t
    state=present

- seport:
    ports={{ fw_galera }}
    proto=udp
    setype=mysqld_port_t
    state=present
