---
# TODO: Check if already registred

- name: Force unregister before register
  redhat_subscription:
    state: absent
  when: use_rhel
  ignore_errors: true

- name: register node with subscription-manager
  redhat_subscription:
    state: present
    username: "{{ rhel_subscription_user }}"
    password: "{{ rhel_subscription_pass }}"
    pool: "{{ rhel_pool_id }}"
  when: use_rhel
  register: subscription
  changed_when: false
  tags:
    - subscribe
    - register

- name: disable all repos
  command: subscription-manager repos --disable=*
  with_items: rhel_repos
  when: use_rhel
  changed_when: false
  tags:
    - subscribe
    - register-repos

- name: enable repos for rhel
  command: subscription-manager repos --enable  {{ item }}
  with_items: rhel_repos
  when: use_rhel
  changed_when: false
  tags:
    - subscribe
    - register-repos
