---

# audit2allow -i /var/log/audit/audit.log -m redis-sentinel
- name: building and installing SELinux module
  copy:
    src=redis-sentinel.te
    dest=/tmp/

- name: check SELinux module redis-sentinel
  command: /usr/bin/checkmodule -M -m -o redis-sentinel.mod /tmp/redis-sentinel.te

- name: check SELinux package redis-sentinel
  command: /usr/bin/semodule_package -m redis-sentinel.mod -o /tmp/redis-sentinel.pp

- name: activate SELinux module redis-sentinel
  command: /usr/sbin/semodule -i /tmp/redis-sentinel.pp

- name: ensure redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644

- name: ensure redis-sentinel is configured
  template:
    src=redis-sentinel.conf.j2
    dest=/etc/redis-sentinel.conf
    mode=0644

- name: create services.d directory to redis-sentinel
  file:
    dest=/etc/systemd/system/redis-sentinel.service.d
    state=directory

- name: set limits to redis-sentinel
  ini_file:
    dest=/etc/systemd/system/redis-sentinel.service.d/limits.conf
    section=Service
    option=LimitNOFILE
    value=10032
  notify: systemctl daemon reload
