---

- name: include redis packages
  include: packages.yml


- name: include redis reset
  include: reset.yml
  when: redis_reset

- name: include redis configuration
  include: configuration.yml

#- name: Ensure redis is running and enabled on boot.
#  service: name="{{ redis_daemon }}" state=started enabled=no

- name: include redis pacemaker
  include: pacemaker.yml
