---

# TODO: Create location to redis and redis-sentinel

- name: stop redis before add to pacemaker
  service: name=redis state=stopped enabled=no

- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  tags:
    - pacemaker
    - pacemaker-redis

- name: create redis cluster resource
  when: ansible_hostname == pacemaker_dc.stdout
  pcs_resource: command=create resource_id=redis type=ocf:heartbeat:redis clone=yes
  args:
    options:
      wait_last_known_master: true
    operations:
      - action: start
        options:
          timeout: 120s
      - action: stop
        options:
          timeout: 120s
      - action: monitor
        options:
          interval: 60s
  tags:
    - pacemaker
    - pacemaker-rabbit

- name: create redis-sentinel cluster resource
  pcs_resource: command=create resource_id=redis-sentinel type=systemd:redis-sentinel clone=yes
  args:
    options:
    operations:
      - action: start
        options:
          timeout: 120s
      - action: stop
        options:
          timeout: 120s
      - action: monitor
        options:
          interval: 60s
  when: ansible_hostname == pacemaker_dc.stdout

