----

- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  tags:
    - pacemaker
    - pacemaker-redis

- name: remove redis from pacemaker
  command: pcs resource delete redis
  when: ansible_hostname == pacemaker_dc.stdout
  ignore_errors: True
  tags:
    - pacemaker
    - pacemaker-redis

- name: remove redis configuration file
  file:
    dest=/etc/redis.conf
    state=absent
  ignore_errors: True
  tags:
    - pacemaker
    - pacemaker-redis
