---

- name: remove redis from pacemaker
  command: pcs resource delete {{ item }}
  when: ansible_hostname == master_server
  with_items:
    - redis
    - redis-sentinel
  ignore_errors: True

- name: remove redis configuration file
  file:
    dest=/etc/redis.conf
    state=absent
  ignore_errors: True
