---

- name: start openvswitch
  service: name=openvswitch state=started enabled=yes
  when: use_neutron
  tags:
    - neutron
    - neutron-basics

- name: Configure neutron
  ini_file: >
    dest=/etc/neutron/neutron.conf
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_options }}"
  tags:
    - neutron
    - neutron-config

- name: Configure metadata
  ini_file: >
    dest=/etc/neutron/metadata_agent.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_metadata_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-metadata

- name: Configure dhcp agent
  ini_file: >
    dest=/etc/neutron/dhcp_agent.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_dhcp_agent_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-dhcp

- name: Configure lbaas agent
  ini_file: >
    dest=/etc/neutron/lbaas_agent.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_lbaas_agent_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-lbaas

- name: Configure l3 agent
  ini_file: >
    dest=/etc/neutron/l3_agent.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_l3_agent_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-l3

- name: Fix perms plugins dir
  file:
    dest=/etc/neutron/plugins/openvswitch
    state=directory
    owner=root
    group=neutron
    recurse=yes
    force=yes
    mode=0755
  tags:
    - neutron
    - neutron-config
    - neutron-ovs

- name: Configure openvswitch plugin
  ini_file: >
    dest=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0644
  with_items: "{{ neutron_ovs_plugin_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-ovs

- name: Configure ml2 plugin
  ini_file: >
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_ml2_plugin_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-ml2

- name: Configure lbaas
  ini_file: >
    dest=/etc/neutron/neutron_lbaas.conf
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_lbaas_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-lbaas

- name: Configure metering agent
  ini_file: >
    dest=/etc/neutron/metering_agent.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=neutron
    owner=root
    mode=0640
  with_items: "{{ neutron_metering_agent_options }}"
  tags:
    - neutron
    - neutron-config
    - neutron-lbaas

- name: Configure dnsmasq options
  copy:
    dest=/etc/neutron/dnsmasq-neutron.conf
    content="{{neutron_dnsmasq_options}}\n"
    mode=0644
    owner=root
    group=neutron
  tags:
    - neutron
    - neutron-config
    - neutron-dnsmasq

- name: Configure neutron sysctl options
  copy:
    dest=/etc/sysctl.d/neutron.conf
    src=neutron-sysctl.conf
    mode=0644
    owner=root
    group=neutron
#  notify: restart neutron server
  tags:
    - neutron
    - neutron-config
    - neutron-sysctl

- name: restart sysctl
  command: sysctl -p
  when: use_neutron
  tags:
    - neutron
    - neutron-deploy
    - neutron-sysctl

- name: link plugin.ini to the ml2 plugin config file
  file:
    src=/etc/neutron/plugins/ml2/ml2_conf.ini
    dest=/etc/neutron/plugin.ini
    state=link
  tags:
    - neutron
    - neutron-ml2

- name: sync neutron database
  command: neutron-db-manage upgrade heads
  when: inventory_hostname == neutron_master

#- name: Patch Controller HA Network
#  copy: src=l3_hamode_db.py dest=/usr/lib/python2.7/site-packages/neutron/db/l3_hamode_db.py mode=0644 owner=root group=root
#
#- name: Patch Lbaas Fail Over
#  copy: src=LbaasCleanup dest=/usr/lib/ocf/resource.d/neutron/LbaasCleanup mode=0777 owner=root group=root
#
#- name: Patch Bin Lbaas Fail Over
#  copy: src=neutron-lbaas-cleanup dest=/usr/bin/neutron-lbaas-cleanup mode=0777 owner=root group=root

