---

- meta: flush_handlers

- name: include neutron packages
  include: packages.yml

- name: include neutron configuration
  include: configuration.yml

- meta: flush_handlers

- name: include neutron reset
  include: reset.yml
  when: neutron_reset

#- name: include neutron pacemaker

- name: Make sure Neutron server is started
  command: systemctl start {{ item }}
  with_items:
    - neutron-server
    - neutron-metadata-agent
    - neutron-dhcp-agent
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-metering-agent
    - neutron-lbaas-agent
