---

- meta: flush_handlers

- name: include neutron packages
  include: packages.yml

- name: include neutron configuration
  include: configuration.yml

- meta: flush_handlers

- name: include neutron reset
  include: reset.yml
  when: neutron_reset

- name: include neutron pacemaker
  include: pacemaker.yml

