---

- name: Make sure Neutron server is disabled and stopped
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - neutron-server
    - neutron-metadata-agent
    - neutron-dhcp-agent
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-metering-agent
    - neutron-lbaas-agent
  tags:
    - pacemaker
    - pacemaker-neutron

- name: create neutron cluster resource
  when: ansible_hostname == master_server
  pcs_resource: command=create resource_id={{ item }} type=systemd:{{ item }} clone=yes
  args:
    options:
    operations:
      - action: monitor
        options:
          interval: 10s
      - action: start
        options:
          timeout: 60s
  with_items:
    - neutron-server
    - neutron-metadata-agent
    - neutron-dhcp-agent
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-metering-agent
    - neutron-lbaas-agent
  tags:
    - pacemaker
    - pacemaker-neutron

- name: create neutron cluster resource
  when: ansible_hostname == master_server
  pcs_resource: command=create resource_id={{ item }} type=systemd:{{ item }}
  args:
    options:
    operations:
      - action: monitor
        options:
          interval: 10s
      - action: start
        options:
          timeout: 60s
  with_items:
    - neutron-lbaas-agent
  tags:
    - pacemaker
    - pacemaker-neutron
