---

- name: install neutron packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-neutron
    - openstack-neutron-openvswitch
    - openstack-neutron-ml2
    - openstack-utils
    - openstack-selinux
    - openvswitch
    - openstack-neutron-lbaas
    - openstack-neutron-metering-agent
  when: use_neutron
