---

openstack_service_env:
  OS_TENANT_NAME: "admin"
  OS_USERNAME: "admin"
  OS_PASSWORD: "{{ keystone_admin_user }}"
  OS_AUTH_URL: "{{ keystone_protocol }}://{{ keystone_internal_vip }}:{{ keystone_admin_port }}/v2.0"
