---

- name: Set service facts
  set_fact: glance_api_service="openstack-glance-api"
  when: ansible_os_family == 'RedHat'

- name: Set service facts
  set_fact: glance_registry_service="openstack-glance-registry"
  when: ansible_os_family == 'RedHat'
