---
# file: roles/rabbitmq/tasks/configuration.yml
- name: Creating SSL folder in /etc/rabbitmq/
  file:
    path=/etc/rabbitmq/ssl
    owner=rabbitmq
    group=rabbitmq
    mode=0750
    state=directory
  when: rabbitmq_ssl
  tags:
    - rabbitmq
    - rabbitmq-ssl

- name: Copying SSL certificates in /etc/rabbitmq/ssl/
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
    owner=rabbitmq
    group=rabbitmq
    mode=0600
  with_items:
    - src: "{{ rabbitmq_cacert_file }}"
      dest: /etc/rabbitmq/ssl/cacert.pem
    - src: "{{ rabbitmq_cert_file }}"
      dest: /etc/rabbitmq/ssl/cert.pem
    - src: "{{ rabbitmq_key_file }}"
      dest: /etc/rabbitmq/ssl/key.pem
  when: rabbitmq_ssl
  tags:
    - rabbitmq
    - rabbitmq-ssl

- name: Configuring SSL for RabbitMQ
  template:
    src=etc/rabbitmq/rabbitmq.config.j2
    dest=/etc/rabbitmq/rabbitmq.config
    owner=rabbitmq
    group=rabbitmq
    mode=0644
  tags:
    - rabbitmq
    - rabbitmq-ssl

- name: Generate environment variables for RabbitMQ
  template:
    src=etc/rabbitmq/rabbitmq-env.conf.j2
    dest=/etc/rabbitmq/rabbitmq-env.conf
    owner=rabbitmq
    group=rabbitmq
    mode=0644
  notify: restart rabbitmq
  when: rabbitmq_conf_env is defined and rabbitmq_env_vars == true
  tags:
    - rabbitmq
    - rabbitmq-env-vars
