---
- name: Install RabbitMQ packages
  yum: pkg={{item}} state=present
  with_items:
    - rabbitmq-server
    - openstack-selinux
  notify: systemctl reload
  tags:
    - rabbitmq
    - rabbitmq-package
