---

- name: include rabbitmq install packages
  include: install.yml

- name: include reset
  include: reset.yml
  when: rabbit_reset

- name: include erlang
  include: erlang.yml

- name: include rabbitmq configuration
  include: configuration.yml

- name: include rabbitmq limits
  include: limits.yml

- name: include rabbitmq firewall
  include: firewall.yml
  when: rabbitmq_firewalld is defined and rabbitmq_firewalld == true

# clustered variable is exported and will be used as a condition
- name: Checking if a RabbitMQ cluster already exists
  stat:
    path=/etc/rabbitmq/clustered
  register: clustered

- name: include rabbitmq clustering configuration
  include: clustering.yml
  when: rabbitmq_reset_cluster is defined and
        rabbitmq_reset_cluster == 'true' and
        rabbitmq_clustering or (clustered.stat.exists != True) and
        rabbitmq_clustering

- name: force rabbitmq stop
  command: pkill -u rabbitmq
  ignore_errors: True

- name: restart all rabbimq servers
  command: systemctl restart rabbitmq-server
  ignore_errors: True

- name: include rabbitmq plugins
  include: plugins.yml

- name: include rabbitmq-server to pacemaker
  include: pacemaker.yml

- name: include rabbitmq vhost
  include: vhosts.yml

- name: include rabbitmq policies
  include: policies.yml

- name: include rabbitmq users
  include: users.yml

- name: include rabbitmq sanity check
  include: sanitycheck.yml
  when: rabbitmq_sanitycheck and
        rabbitmq_clustering or (clustered.stat.exists != True)
