---
- include: install.yml
- include: erlang.yml
- include: configuration.yml
- include: limits.yml

- include: firewall.yml
  when: rabbitmq_firewalld is defined and rabbitmq_firewalld == true

# clustered variable is exported and will be used as a condition
- name: Checking if a RabbitMQ cluster already exists
  stat:
    path=/etc/rabbitmq/clustered
  register: clustered

- include: clustering.yml
  when: rabbitmq_reset_cluster is defined and
        rabbitmq_reset_cluster == 'true' and
        rabbitmq_clustering or (clustered.stat.exists != True) and
        rabbitmq_clustering

- include: plugins.yml
- include: vhosts.yml
- include: policies.yml
- include: users.yml

- name: restart all rabbimq servers
  command: systemctl restart rabbitmq-server

- include: sanitycheck.yml
  when: rabbitmq_sanitycheck and
        rabbitmq_clustering or (clustered.stat.exists != True)
