---
- name: stop rabbitmq before add to pacemaker
  service: name=rabbitmq-server state=stopped enabled=no

- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  tags:
    - pacemaker
    - pacemaker-galera

- name: create rabbitmq cluster resource
  when: ansible_hostname == pacemaker_dc.stdout
  pcs_resource: command=create resource_id=rabbitmq type=ocf:heartbeat:rabbitmq-cluster
  args:
    options:
    operations:
      - action: monitor
        options:
          interval: 40s
      - action: start
        options:
          timeout: 60s
  tags:
    - pacemaker
    - pacemaker-rabbit

- name: clone rabbitmq pacemaker
  command: pcs resource clone rabbitmq
  tags:
    - pacemaker
    - pacemaker-rabbitmq
