---
- name: stop rabbitmq before add to pacemaker
  service: name=rabbitmq-server state=stopped enabled=no

- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  tags:
    - pacemaker
    - pacemaker-galera
    - pacemaker-rabbitmq

- name: create rabbitmq cluster resource
  when: ansible_hostname == pacemaker_dc.stdout
  pcs_resource: command=create resource_id=rabbitmq type=systemd:rabbitmq-server clone=yes
  args:
    options:
    operations:
      - action: monitor
        options:
          interval: 40s
      - action: start
        options:
          timeout: 60s
  tags:
    - pacemaker
    - pacemaker-rabbit

- name: pause to start rabbitmq services
  pause: seconds=30

- name: create policy to ha
  command:  rabbitmqctl set_policy ha-all "^ha\." '{"ha-mode":"all"}'
  tags:
    - pacemaker
    - pacemaker-rabbitmq
