---

- name: Configure nova
  ini_file: >
    dest=/etc/nova/nova.conf
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=nova
    owner=root
    mode=0640
  with_items: "{{ nova_options }}"

- name: Configure nova api paste
  ini_file: >
    dest=/etc/nova/api-paste.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=nova
    owner=root
    mode=0640
  with_items: "{{ nova_api_options }}"

- name: sync nova database
  command: nova-manage db sync
  when: inventory_hostname == keystone_master
