---

- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  ignore_errors: True
  no_log: True
  tags:
    - pacemaker


- name: remove nova services from pacemaker
  command: pcs resource delete {{ item }}
  with_items:
    - nova-scheduler
    - nova-api
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
  tags:
    - pacemaker
    - pacemaker-nova
