---
- name: deploy ceilometer config file
  file:
    src=ceilometer.conf.j2
    dest=/etc/ceilometer/ceilometer.conf
    mode=0640
    owner=root
    group=ceilometer
  tags:
    - ceilometer
    - ceilometer-deploy

- name: configure ceilometer
  ini_file: >
    dest=/etc/ceilometer/ceilometer.conf
     section={{ item.section }}
     option={{ item.option }}
     value={{ item.value }}
     state={{ item.state |default('present')}}
     owner=root
     group=ceilometer
     mode=0640
  with_items: "{{ ceilometer_options }}"
  ##no_log: True
  tags:
    - ceilometer
    - ceilometer-config
    - ceilometer-api-config
