---

- name: stop and disable ceilometer services
  service: name=openstack-{{ item }} state=stopped enabled=no
  with_items:
    - ceilometer-central
    - ceilometer-collector
    - ceilometer-api
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - ceilometer-notification
    - ceilometer-polling
  ignore_errors: True

- name: create pacemaker resource for ceilometer
  pcs_resource: command=create name={{ item }} type=systemd:openstack-{{ item }} clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  when: ansible_hostname == master_server
  with_items:
    - ceilometer-central
    - ceilometer-collector
    - ceilometer-api
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - ceilometer-notification
    - ceilometer-polling
