---

- name: install ceilometer packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-ceilometer-common
    - openstack-ceilometer-api
    - openstack-ceilometer-central
    - openstack-ceilometer-collector
    - openstack-ceilometer-alarm
    - openstack-ceilometer-notification
    - python-ceilometer
    - python-ceilometerclient
    - python-oslo-policy
    - python-redis
