---

- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  ignore_errors: True
  ##no_log: True
  tags:
    - pacemaker

- name: remove ceilometer services from pacemaker
  command: pcs resource delete {{ item }}
  when: ansible_hostname == pacemaker_dc.stdout
  with_items:
    - ceilometer-central
    - ceilometer-collector
    - ceilometer-api
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - ceilometer-notification
    - ceilometer-polling
  ignore_errors: True
