---

- name: remove ceilometer services from pacemaker
  command: pcs resource delete {{ item }}
  when: ansible_hostname == master_server
  with_items:
    - ceilometer-central
    - ceilometer-collector
    - ceilometer-api
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - ceilometer-notification
    - ceilometer-polling
  ignore_errors: True
