---

- name: listen on all interfaces
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen " insertafter="^#Listen " line="Listen 0.0.0.0:80"
  notify: restart httpd
  tags: horizon

- name: deploy openstack-dashboard local settings
  template: src=local_settings.j2 dest=/etc/openstack-dashboard/local_settings mode=0640 owner=root group=apache
  notify: restart horizon
  tags: horizon

- name: copy httpd openstack-dashboard.conf
  copy: src=openstack-dashboard.conf dest=/etc/httpd/conf.d/openstack-dashboard.conf mode=0644
  notify: restart horizon
  tags: horizon

- name: copy performancetunning.conf
  copy: src=02-performancetunning.conf dest=/etc/httpd/conf.modules.d/02-performancetunning.conf mode=0644
  notify: restart horizon
  tags: horizon

- name: Limits httpd
  copy: src=httpd.service dest=/usr/lib/systemd/system/httpd.service mode=0644
  tags: horizon
