---

- name: remove welcome
  file: path=/etc/httpd/conf.d/welcome.conf state=absent

- name: remove dashboard.conf
  file: path=/etc/httpd/conf.d/dashboard.conf state=absent

- name: listen on all interfaces
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "^Listen "
    insertafter: "^#Listen "
    line: "Listen {{ internal_ip }}:80"

- name: deploy openstack-dashboard local settings
  template:
    src: local_settings.j2
    dest: /etc/openstack-dashboard/local_settings
    mode: 0640
    owner: root
    group: apache

- name: copy httpd openstack-dashboard.conf
  copy:
    src: openstack-dashboard.conf
    dest: /etc/httpd/conf.d/openstack-dashboard.conf
    mode: 0644

- name: copy performancetunning.conf
  copy:
    src: 02-performancetunning.conf
    dest: /etc/httpd/conf.modules.d/02-performancetunning.conf
    mode: 0644

- name: create systemd directory for httpd
  file:
    path: /etc/systemd/system/httpd.service.d
    state: directory

- name: Increase httpd file limit via Systemd
  copy:
    src: httpd-limits.conf
    dest: /etc/systemd/system/httpd.service.d/limits.conf
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  command: systemctl daemon-reload

- name: create horizon secret file
  copy:
    dest: /var/lib/openstack-dashboard/.secret_key_store
    content: "{{ horizon_secret_key }}"
    mode: 0600
    owner: apache
    group: apache
