---

- include: packages.yml

- include: reset.yml
  when: network_reset

- include: openvswitch.yml
  when: use_openvswitch

- include: bond.yml
  when: network_bond_interfaces is defined and network_bond_interfaces |length > 0

- include: ethernet.yml
  when: network_ether_interfaces is defined and network_ether_interfaces |length > 0

- include: bridge.yml
  when: network_bridge_interfaces is defined and network_bridge_interfaces |length > 0

