---

- include: packages.yml

- include: reset.yml
  when: network_reset

- include: openvswitch.yml
  when: use_openvswitch

- include: bond.yml
  when: network_bond_interfaces is defined and network_bond_interfaces |length > 0

- include: ethernet.yml
  when: network_ether_interfaces is defined and network_ether_interfaces |length > 0

- include: bridge.yml
  when: network_bridge_interfaces is defined and network_bridge_interfaces |length > 0

- name: Set hostname
  hostname: name={{ inventory_hostname }}

- name: set resolv.conf
  template:
    src=resolv.conf.j2
    dest=/etc/resolv.conf
    mode=0644

- name: disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: restart network
  service: name=network state=restarted enabled=yes

- name: setup kernel modules
  modprobe: name={{ item }} state=present
  with_items:
    - nf-conntrack
    - nf_conntrack_ipv4
    - nf_conntrack_ipv6
    - nf_conntrack_pptp
    - vhost_net

- name: set sysctl parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
    ignoreerrors: yes
  with_items: net_os_tuning_params
