---
- name: enable and start openvswitch
  service:
    name: openvswitch
    state: started
    enabled: yes
  when: use_openvswitch

- name: create integration bridge legacy
  openvswitch_bridge:
    bridge: br-int
    state: present
  when: use_openvswitch

- name: create tunneling bridge legacy
  openvswitch_bridge:
    bridge: br-tun
    state: present
  when: neutron_ovs_tunnel_type is defined

- name: create external network bridge
  openvswitch_bridge:
    bridge: "{{ neutron_external_bridge | default('br-ex') }}"
    state: present
  ignore_errors: yes
  when: use_neutron_l3

- name: create ovs bridges pnet1
  openvswitch_bridge:
    bridge: "{{ item }}"
    state: present
  with_items: neutron_ovs_bridges
  when: use_openvswitch

- name: configure ovs ports physical net
  openvswitch_port:
    bridge: "{{ neutron_ovs_bridges }}"
    port: "{{ pnet_interface }}"
    state: present
  when: use_openvswitch
  ignore_errors: True

- name: configure ovs ports
  openvswitch_port:
    bridge: "{{ neutron_external_bridge | default('br-ex') }}"
    port: "{{ ext_interface }}"
    state: present
  when: use_openvswitch and ext_interface is defined
  ignore_errors: True
