---

- name: remove NetworkManager
  yum:
    name: NetworkManager
    state: removed

- name: Install the required  packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: network_packages

- name: Install openvswitch if required
  when: use_openvswitch
  yum:
    name: openvswitch
    state: installed
  notify: restart openvswitch

