---

- name: set haproxy sysctl parameters
  sysctl: name=net.ipv4.ip_nonlocal_bind value=1 state=present sysctl_set=yes reload=yes

- name: SELinux for haproxy
  command: setsebool -P haproxy_connect_any on

- name: set haproxy config file
  template:
     dest=/etc/haproxy/haproxy.cfg
     src=haproxy.cfg.j2
  notify: restart haproxy

- name: create pki directory for haproxy ssl termination
  file: path=/etc/pki/haproxy state=directory owner=root group=root mode=0755
  when: use_haproxy_ssl_termination

- name: deploy certificate file for ssl termination
  copy: src=credentials/haproxy/cert.pem dest=/etc/pki/haproxy/cert.pem mode=0600
  when: use_haproxy_ssl_termination
  notify: restart haproxy

- name: deploy certificate file for ssl termination
  copy: src=credentials/haproxy/cert.pem-lab dest=/etc/pki/haproxy/cert.pem mode=0600
  when: use_haproxy_ssl_termination
  notify: restart haproxy

- name: disable haproxy service
  service: name=haproxy enabled=no

- name: configure rsyslog to haproxy
  copy:
    src=haproxy-rsyslog.conf
    dest=/etc/rsyslog.d/haproxy.conf
  notify: restart rsyslog

#- name: configure logrotate to haproxy
#  file:
#    src=haproxy-logrotate.conf
#    dest=/etc/logrotate.d/haproxy.conf
#  notify: restart rsyslog
