---

- name: create haproxy cluster resource
  when: ansible_hostname == master_server
  pcs_resource: command=create resource_id=haproxy type=systemd:haproxy clone=yes
  args:
    options:
    operations:
      - action: monitor
        options:
          interval: 10s
      - action: start
        options:
          timeout: 60s

- name: create constraint vib-db and haproxy
  command: pcs constraint colocation add vip-db haproxy-clone INFINITY
  ignore_errors: True
  register: command_result
  when: ansible_hostname == master_server
  failed_when: "'FAILED' in command_result.stderr"

- name: create order constraint
  command: pcs constraint order vip-db then haproxy-clone kind=Optional
  ignore_errors: True
  when: ansible_hostname == master_server
  failed_when: "'FAILED' in command_result.stderr"
