---
- name: Get Current DC
  shell: pcs status cluster | awk '/^ Current DC:/ {print $3}'
  register: pacemaker_dc
  tags:
    - pacemaker
    - pacemaker-haproxy

- name: remove haproxy from pacemaker
  command: pcs resource delete haproxy
  when: ansible_hostname == pacemaker_dc.stdout
  ignore_errors: True

- name: remove haproxy configurations
  file:
    dest=/etc/haproxy/haproxy.cfg
    state=absent

- name: remove haproxy ssl directory
  file:
    dest=/etc/pki/haproxy
    state=absent
  when: use_haproxy_ssl_termination

- name: remove haproxy from pacemaker
  command: pcs resource delete haproxy
  ignore_errors: True
  #no_log: True
