---

- name: configure ceilometer
  ini_file: >
    dest=/etc/ceilometer/ceilometer.conf
     section={{ item.section }}
     option={{ item.option }}
     value={{ item.value }}
     state={{ item.state |default('present')}}
     owner=root
     group=ceilometer
     mode=0640
  with_items: "{{ ceilometer_options }}"


#- name: configure ceilometer
#  template: src=ceilometer.conf.j2 dest=/etc/ceilometer/ceilometer.conf mode=0644 owner=root group=ceilometer backup=yes
