---

- name: Configure nova
  ini_file: >
    dest=/etc/nova/nova.conf
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=nova
    owner=root
    mode=0640
  with_items: "{{ nova_options }}"

