---

- name: remove heat from pacemaker
  command: pcs resource delete {{ item}}
  when: inventory_hostname == heat_master
  ignore_errors: True
  with_items:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - heat-engine
  tags: heat

- name: remove heat configuration file
  file:
    dest: /etc/heat/heat.conf
    state: absent
  ignore_errors: True
  tags:
    - heat

- name: Removing heat default database
  mysql_db:
    name: "{{ db_heat_name }}"
    state: absent
  when: inventory_hostname == heat_master
  ignore_errors: True

- name: Make sure the heat database is present
  mysql_db:
    name: "{{ db_heat_name }}"
    collation: 'utf8_general_ci'
    encoding: "utf8"
    state: present
  when: inventory_hostname == heat_master
  ignore_errors: True
