---
- hosts: controller
  gather_facts: True
  roles:
    - rh-network # OK
    - rh-pacemaker # OK
    - rh-haproxy
    - rh-galera
    - rh-rabbitmq
    - rh-memcached
#    - rh-keystone
#    - rh-glance
#    - rh-cinder
#    - rh-nova-control
#    - rh-neutron
#    - rh-horizon
#    - rh-nova-common
#    - rh-heat
#    - rh-horizon
#    - rh-mongodb
#    - rh-ceilometer
#    - rh-controller
