---
- hosts: controller
  gather_facts: True
  roles:
    - rh-network
    - rh-pacemaker

#    - rh-rabbitmq
#    - rh-galera
#    - rh-memcached
#    - rh-keystone
#    - rh-glance
#    - rh-cinder
#    - rh-nova-control
#    - rh-neutron
#    - rh-horizon
#    - rh-nova-common
#    - rh-heat
#    - rh-horizon
#    - rh-mongodb
#    - rh-ceilometer
#    - rh-controller
