---

- name: Configure Cinder API
  ini_file: >
    dest=/etc/cinder/cinder.conf
     section={{ item.section }}
     option={{ item.option }}
     value={{ item.value }}
     state={{item.state| default('present')}}
  with_items: "{{ cinder_options }}"

- name: start cinder services
  service: name={{ item }} state=started enabled=no
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume

- name: audit volume usage crontab
  cron: minute="0" hour="*" weekday="*"
        name="Audit cinder volume usage"
        cron_file="CinderVolumeUsage"
        user="root"
        job="PYTHONIOENCODING=utf-8 /usr/bin/cinder-volume-usage-audit"
