---

- meta: flush_handlers

- name: include cinder facts
  include: facts.yml

- name: include cinder packages
  include: packages.yml

- name: include cinder reset
  include: reset.yml
  when: cinder_reset

- name: include cinder configuration
  include: configuration.yml

- name: Sync Cinder database
  cinder_manage: action=db_sync
  sudo: no
  sudo_user: cinder
  when: cinder_bootstrap and
        inventory_hostname == cinder_master

- name: include cinder storage
  include: storage.yml
  when: cinder_storage_backend |length > 0

- name: include cinder pacemaker
  include: pacemaker.yml
