---
- name: install cinder packages
  yum: pkg={{ item }} state=present
  with_items:
    - iscsi-initiator-utils
    - openstack-cinder
    - openstack-utils
    - openstack-selinux
    - python-cinder
    - python-cinderclient
  tags: cinder

