---

- name: Removing cinder default database
  mysql_db:
    name: "cinder"
    state: absent
  when: inventory_hostname == cinder_master
  ignore_errors: True

- name: Make sure the cinder database is present
  mysql_db:
    name: "cinder"
    collation: 'utf8_general_ci'
    encoding: "utf8"
    state: present
  when: inventory_hostname == cinder_master
  ignore_errors: True

- name: remove cinder configuration
  file: state=absent path=/etc/cinder/{{ item }}
  with_items:
    - "cinder.conf"
  ignore_errors: True

- name: Remove cinder pacemaker resource
  command: pcs resource delete {{ item }}
  when: inventory_hostname == cinder_master
  with_items:
    - cinder-scheduler
    - cinder-api
    - cinder-volume
  ignore_errors: True
