---

- name: Configure storage LVM
  ini_file: >
    dest=/etc/cinder/cinder.conf
     section={{ item.section }}
     option={{ item.option }}
     value={{ item.value }}
     state={{item.state| default('present')}}
  with_items: "{{ cinder_storage_backend }}"
  when: cinder_storage_backend |length > 0
  notify: restart cinder volume
  tags:
    - cinder
    - cinder-lvm

# TODO: create new method to deploy this
- name: Create Storage type
  shell: cinder type-create {{ item.name }}
  run_once: true
  environment: openstack_service_env
  ignore_errors: True
  with_items: cinder_storage_types
  when: cinder_storage_types |length > 0
  notify: restart cinder volume
  tags:
    - cinder
    - cinder-lvm
    - cinder-type

- name: Create storage type spec
  shell: cinder type-key {{ item.name }} set volume_backend_name={{ item.volume_backend_name }}
  environment: openstack_service_env
  run_once: true
  ignore_errors: True
  with_items: cinder_storage_types
  when: cinder_storage_types |length > 0
  notify: restart cinder volume
  tags:
    - cinder
    - cinder-lvm
    - cinder-type
