---

- name: create the keyfile for authentication
  copy:
    dest=/var/lib/mongodb/secret
    content="{{ mongodb_secrets }}"
    owner=mongodb
    group=mongodb
    mode=0600
  tags: mongodb

- name: Ensure dbpath directory
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    owner: mongodb
    recurse: yes

- name: restore file(s) default SELinux security contexts
  command: restorecon {{ mongodb_db_path }}

- name: create the mongodb configuration file
  template: src=mongodb.conf.j2 dest=/etc/mongod.conf
  tags: mongodb

- name: copy limits mongodb
  copy: src=mongodb-limits.conf dest=/etc/security/limits.d/30-mongodb.conf mode=0644 owner=root group=root
  tags: mongodb

- name: start the mongodb service
  service: name=mongod state=started
  tags: mongodb

- name: Wait when mongodb is started
  wait_for:
    host: "{{ wait_for_host | default(mongodb_bind_host) }}"
    port: "{{ mongodb_port }}"
    timeout: 120
