---

- name: stop the mongodb service
  service: name=mongod state=stopped enabled=no

- name: create mongod cluster resource
  when: ansible_hostname == master_server
  pcs_resource: command=create resource_id=mongodb type=systemd:mongod clone=yes
  args:
    options:
    operations:
      - action: monitor
        options:
          interval: 10s
      - action: start
        options:
          timeout: 60s
