---

#
# Copyright (c) 2015 Davide Guerri <davide.guerri@gmail.com>
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: copy default keystone.conf
  copy:
    src=keystone.conf
    dest=/etc/keystone/keystone.conf
    mode=644
    owner=keystone
    group=keystone


- name: disable httpd listen 80
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp="^Listen 80"
    line="#Listen 80"

- name: set ServerName directive
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp="^#ServerName www.example.com:80"
    line="ServerName {{ inventory_hostname}}"

- name: Configure keystone
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=apache
    owner=keystone
    mode=0644
  with_items: "{{ keystone_options }}"
  no_log: True
  tags:
    - keystone
    - keystone-config

#- name: Configure keystone
#  template:
#    src=keystone.conf.j2
#    dest=/etc/keystone/keystone.conf
#    owner=keystone
#    group=keystone
#    mode=0640
#  tags:
#    - keystone
#    - keystone-config

- name: Configure keystone-paste
  template:
    src=keystone-paste.ini
    dest=/etc/keystone/keystone-paste.ini
    owner=keystone
    group=keystone
    mode=0640
  no_log: True
  tags:
    - keystone
    - keystone-config

- name: Configure keystonerc_admin
  template:
    src=keystonerc_admin.j2
    dest=/root/keystonerc_admin
    owner=keystone
    group=keystone
    mode=0640
  no_log: True
  tags:
    - keystone
    - keystone-config

- name: FIX BUG KEYSTONE MANAGE SYNC DB OpenStack 8
  file:
    src=engines.py
    dest=/usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py
    mode=0644
    owner=root
    group=root
  when: openstack_version == 8
  no_log: True

- name: Sync Keystone database
  command: keystone-manage db_sync
  sudo: no
  sudo_user: keystone
  when: inventory_hostname == keystone_master

#- name: Configure keystone to be verbose
#  when: keystone_verbose
#  ini_file:
#    dest=/etc/keystone/keystone.conf
#    section=DEFAULT
#    option=verbose
#    value=True
#  notify:
##    - Sync Keystone database
#    - Restart Apache

#- name: Configure keystone to be debug
#  ini_file:
#    dest=/etc/keystone/keystone.conf
#    section=DEFAULT
#    option=debug
#    value=True
#  notify:
##    - Sync Keystone database
#    - Restart Apache
#
#- name: Restart apache
#  command: systemctl restart httpd
