---

- name: copy default keystone.conf
  copy:
    src=keystone.conf
    dest=/etc/keystone/keystone.conf
    mode=644
    owner=keystone
    group=keystone


- name: disable httpd listen 80
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp="^Listen 80"
    line="#Listen 80"

- name: set ServerName directive
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp="^#ServerName www.example.com:80"
    line="ServerName {{ inventory_hostname}}"

- name: Configure keystone
  ini_file:
    dest=/etc/keystone/keystone.conf
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    state={{item.state| default('present')}}
    group=apache
    owner=keystone
    mode=0644
  with_items: "{{ keystone_options }}"

- name: Configure keystone-paste
  template:
    src=keystone-paste.ini
    dest=/etc/keystone/keystone-paste.ini
    owner=keystone
    group=keystone
    mode=0640

- name: Configure keystonerc_admin
  template:
    src=keystonerc_admin.j2
    dest=/root/keystonerc_admin
    owner=keystone
    group=keystone
    mode=0640

- name: FIX BUG KEYSTONE MANAGE SYNC DB OpenStack 8
  file:
    src=engines.py
    dest=/usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py
    mode=0644
    owner=root
    group=root
  when: openstack_version == 8

- name: Sync Keystone database
  keystone_manage: action=dbsync
  when: inventory_hostname == keystone_master
