---

- name: Create Keystone endpoints
  keystone_service: >
    token="{{ keystone_admin_token }}"
    name="{{ item.service_name }}"
    type="{{ item.service_type }}"
    description="{{ item.description|default('Not provided') }}"
    public_url="{{ item.public_url }}"
    internal_url="{{ item.internal_url }}"
    admin_url="{{ item.admin_url }}"
    region="{{ item.region|default(keystone_default_region) }}"
    endpoint="{{ keystone_protocol }}://{{ internal_ip }}:{{ keystone_admin_port }}/{{ keystone_api_version }}"
    state="{{ item.state|default('present') }}"
  with_items: "{{ keystone_endpoints }}"
  when: inventory_hostname == keystone_master
  ignore_errors: True
  #no_log: True
  tags: endpoints2

