---

- meta: flush_handlers

- include: facts.yml
- include: packages.yml

- include: reset.yml
  when: keystone_reset and inventory_hostname == keystone_master
  tags:
    - keystone
    - keystone-reset

- include: configuration.yml
- include: wsgi.yml

- meta: flush_handlers

- name: Ensure that the Keystone service is stopped
  service: name={{ keystone_service }} state=stopped enabled=no

- name: Restart httpd
  service: name=httpd state=restarted enabled=no

- name: Fix permission to keystone.log
  file:
    dest: /var/log/keystone/keystone.log
    mode: 0644
    owner: keystone
    group: keystone

- name: Include keystone maintenance
  include: maintenance.yml

- name: Include keystone endpoints
  include: endpoints.yml
  tags:
    - endpoints
    - keystone
    - endpoints2

- name: Include keystone tenants
  include: tenants.yml

- name: Include keystone users
  include: users.yml

- name: Include keystone roles
  include: roles.yml

- name: Include keystone cleanup
  include: cleanup.yml
  when: keystone_disable_auth_token

- name: Include keystone sanity check
  include: sanitycheck.yml
  when: keystone_run_sanity_check
  tags:
    - sanity-check

- name: Include keystone pacemaker
  include: pacemaker.yml
  tags:
    - pacemaker-keystone
