---

- name: remove httpd from boot
  service: name=httpd state=stopped enabled=no

- name: create httpd pacemaker
  pcs_resource: command=create resource_id=keystone type=systemd:httpd clone=yes
  when: ansible_hostname == master_server

- name: create galera-master constraint to keystone
  command: pcs constraint order promote galera-master then keystone-clone kind=Optional
  when: ansible_hostname == master_server

- name: create memcached constraint to keystone
  command: pcs constraint order memcached-clone then keystone-clone kind=Optional
  when: ansible_hostname == master_server

- name: create rabbitmq constraint to keystone
  command: pcs constraint order rabbitmq-clone then keystone-clone kind=Optional
  when: ansible_hostname == master_server

- name: create vip-pub-keystone constraint to keystone
  command: pcs constraint order vip-pub-keystone then keystone-clone kind=Optional
  when: ansible_hostname == master_server

- name: create haproxy constraint to keystone
  command: pcs constraint order haproxy-clone then keystone-clone kind=Optional
  when: ansible_hostname == master_server

