---
- name: remove WSGI keystone configuration
  file: state=absent path=/etc/http/conf.d/wsgi-keystone.conf

- name: remove WSGI configuration dir
  file: state=absent path={{ keystone_cgibin_dir }}

#- name: Remove keystone configuration file
#  file: state=absent path={{ item }}
#  with_items:
#    - "/etc/keystone/keystone.conf"
#    - "policy.json"

- name: Removing keystone default database
  mysql_db:
    name: keystone
    state: absent
  run_once: True

- name: remove keystone from pacemaker
  command: pcs resource delete keystone
  ignore_errors: True


- name: disable httpd listen 80
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp="^Listen 80"
    line="#Listen 80"
  ignore_errors: True

- name: set ServerName directive
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    regexp="^#ServerName www.example.com:80"
    line="ServerName {{ inventory_hostname}}"

- name: Restart httpd
  command: systemctl restart httpd
  ignore_errors: True

- name: Removing keystone database
  mysql_db:
    name: keystone
    state: present
  run_once: True

- name: Make sure the keystone database is present
  mysql_db:
    name: 'keystone'
    collation: 'utf8_general_ci'
    encoding: "utf8"
    state: present

