---

- name: Add Keystone roles to defined users in defined tenants
  keystone_user: >
    role="{{ item.name }}"
    user="{{ item.user }}"
    tenant="{{ item.tenant }}"
    endpoint="{{ keystone_protocol }}://{{ internal_ip }}:{{ keystone_admin_port }}/{{ keystone_api_version }}/"
    token="{{ keystone_admin_token }}"
    state="{{ item.state|default('present') }}"
  register: result
  until: not result|failed
  retries: "{{ keystone_api_retries }}"
  delay: "{{ keystone_api_retries_delay }}"
  with_items: "{{ keystone_roles }}"
  when: inventory_hostname == keystone_master
  #no_log: True
