---

- name: Create Keystone users
  keystone_user: >
    user="{{ item.name }}"
    password="{{ item.password }}"
    tenant="{{ item.tenant }}"
    email="{{ item.email|default('nobody@localhost') }}"
    endpoint="{{ keystone_protocol }}://{{ keystone_internal_vip }}:{{ keystone_admin_port }}/{{ keystone_api_version }}"
    token="{{ keystone_admin_token }}"
    state="{{ item.state|default('present') }}"
  with_items: "{{ keystone_users }}"
  register: result
  until: not result|failed
  retries: "{{ keystone_api_retries }}"
  delay: "{{ keystone_api_retries_delay }}"
  when: inventory_hostname == keystone_master
